module Messenger {

  @topic
  struct Message {
    string from;
    string subject;
    @key long subject_id;
    string text;
    long count;
    long count2;
  };
};

module Apa {

  @topic
  struct Message2 {
    string from;
    string subject;
    @key long subject_id;
    string text;
    long count;
    long count2;
  };
};